name: Build website preview

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  website:
    name: Build website
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install NodeJS
        uses: actions/setup-node@v5
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: |
          npm install

      - name: Build
        run: |
          npm run build

      - name: Commit website preview
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout --orphan gh-pages
          git rm -rf .
          mv dist/* .
          rm -rf node_modules/
          # Change locales/fr.js to locales/en.js
          sed -i 's/locales\/fr.js/locales\/en.js/g' index.html
          git add .
          git commit -a -m "Update website preview"
          git push --force origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
